### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by tokar86a** [dandesousa/discord-raid-coordinator#28]
I get this error:

Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py>=0.16.8->discord-raid-coordinator)
  Using cached aiohttp-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LHFRrP/aiohttp/setup.py", line 60, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LHFRrP/aiohttp/

My version i use is Python 3.5.2

What is the problem?

**Comment by dandesousa** [comment]
hmm are you installing this in a virtualenv? Perhaps pip is pointing to python 2?

**Comment by tokar86a** [comment]
Yes i try to do that. I dont know where the pip is pointed.

**Comment by dandesousa** [comment]
http://docs.python-guide.org/en/latest/dev/virtualenvs/

To ensure you are using the right version of python.

**Comment by tokar86a** [comment]
C:\Python35>python --version
Python 3.5.4

**Comment by tokar86a** [comment]
Get it to work now.

**Comment by dandesousa** [comment]
Do you mean you got it to work now?

**Comment by dandesousa** [comment]
This points to an environment issue, as it fails installing a dependent library, not on my code. 

```
 File "", line 1, in 
File "/tmp/pip-build-LHFRrP/aiohttp/setup.py", line 60, in 
raise RuntimeError("aiohttp requires Python 3.4.2+")
RuntimeError: aiohttp requires Python 3.4.2+
```

Your pip is not pointing to that python. Check the version of python in the environment you made or if you have multiple python installs.
