### ISSUE TITLE
TimeZone

### ISSUE THREAD

**Issue by tokar86a** [dandesousa/discord-raid-coordinator#30]
Hi

Can i somehow change the timezone on the clock?  

This time 
started at
2017-09-10 02:18:40 PM

Is completely wrong.

**Comment by dandesousa** [comment]
Timezone is currently defaulted to US/Eastern, its a simple change to add this as an argument and use that as the default. If you wanna do a PR or I can add this next time I make a change to the bot.

**Comment by divnotded** [comment]
Was this change ever implemented, lost trying to solve this myself. 
![capture](https://user-images.githubusercontent.com/20913034/35853205-bed966da-0ae1-11e8-878f-b121609e6eb1.JPG)

**Comment by dandesousa** [comment]
This was fixed in the `master` with the `--time-zone` flag. For valid arguments see:

https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
