### ISSUE TITLE
Add ability to transfer egg chat to raid chat

### ISSUE THREAD

**Issue by drunkenslang** [dandesousa/discord-raid-coordinator#35]
So now that eggs are back, my users like setting up before a raid egg hatches.  Would it be possible to say have a chat open when a raid egg hatches (called out by pokeakarm), then when said egg hatches have pokeakarm call out with the hatched Pokemon and use the original egg channel.  Not sure if it's possible, but just an idea.

**Comment by dandesousa** [comment]
Sorry for the long delay -- its a good idea but not one that fits in well with the current way the bot functions. I am going to be releasing a new bot in the coming weeks which will be hosted for discords and will keep this in mind.
