### ISSUE TITLE
Starting a new raid regex

### ISSUE THREAD

**Issue by Fabio1988** [dandesousa/discord-raid-coordinator#36]
Bot is running, he has all permissions on the discord server, he is member on the server (also online when started). but he doesn't do anything.
On starting the bot this message appears:

> 1 raid channel(s)
> raid channel: raid-group-this-city
> raid viewer role: raid-viewer
> raid organizer role: raid-organizer

I write

> !raid-lugia at XXX, disappears at 8pm

also

> @raid-lugia at XXX, disappears at 9pm

and

> raid-lugia at XXX, disappears at 7pm

do I have to trigger the raid in another way?
Maybe a better documentation for this. Do I have to implement roles for every pokemon? so raid-lugia is a role on the server? I also tried this, but doesn't work.

**Comment by Fabio1988** [comment]
I'm looking forward to an answer. Can you explain pls?

**Comment by divnotded** [comment]
@Fabio1988 I was having same issue you have to create the roles for the raids that you want available eg:raid-lugia, raid-kyogre I thought it was automatic also until I tried it.

**Comment by Fabio1988** [comment]
@divnotded Hy, thanks for your answer :)
I also created a role with "raid-lugia"
This role doesn't have a member, or must the bot be a member of it?
So I write down:
_@raid-lugia CITY-STREET, disappears at 1pm_

**Comment by divnotded** [comment]
no it is listening for the @role-raidboss mention no members are assigned to it I am still having issues wth time being off have you figured that out

**Comment by Fabio1988** [comment]
i have a role "raid-kyogre" but I have to say "Allow Anyone to Mention This Role" for this role, so I can use @raid-kyogre... But nothing is happen when I write. Can you please explain exactly? sorry.

**Comment by dandesousa** [comment]
Are you announcing it in a channel where the bot has the following permissions:

```
To test the bot, you will need to enable it to announce raids on a channel-by-channel basis.

The bot requires read and manage message permissions in any channel its capable of announcing raids.
```

http://discord-raid-coordinator.readthedocs.io/en/latest/

**Comment by dandesousa** [comment]
The bot needs manage message permissions in the channel in which it announces raids, since it works by updating the message when the raid is complete

**Comment by Fabio1988** [comment]
The bot have all permissions for reading and managing.. 
further for testing I gave the bot all permissions. But nothing happened.
In the channel raid-group-city he also had the permissions.

Also I tested for creating "roles" for "raid-kyogre", is this neccessary? But this also doesn't work.

How do I have to write the commands? as mentioned above, I tried those comments, but nothing happen.

**Comment by Fabio1988** [comment]
I used it on Ubuntu and Windows... I don't tried it out on a server yet.. for testing I keep it on local machine

**Comment by dandesousa** [comment]
Invite me to your discord server and I can help you examine the permissions

**Comment by opensore** [comment]
Hello.  I just started setting up this discord bot and see a similar issue.  Were you able to resolve this?  What did you find to be the issue?

Thanks

**Comment by Fabio1988** [comment]
I couldn't fix it. I deleted the bot right after, dandesousa's offer for inviting him to my discord was after deleting it.
Maybe he can help you... I would looking forward for a solution.

**Comment by dandesousa** [comment]
If people want guidance on this I can help out by adding me to a server and I can assist with debugging. Though to be honest I am about to stop maintaining the project, since I'm on the verge of launching a hosted re-written version of the bot. If people want a low dependency self-hosted version they can run this or Meowth.

Either way I'll help if I can.

**Comment by dandesousa** [comment]
https://pokenavbot.com

This is the rewritten but closed source version of the bot -- much improved and used by hundreds of servers. Closing this issue -- this project will no longer be maintained
